### PR TITLE
Update ercf.py

### PR DESCRIPTION
**Pull request by Jaans**
Allow for 2 decimals when setting TMC DRIVER CURRENT to support for more fine grained stepper current reduction during extruder collision detection. Also some minor spelling and anal retentiveness.

### CODE REVIEW

**Comment by Jaans** [comment]
Additional README.md updates for spelling and typos only.

**Review by moggieuk — APPROVED** [review]
The improved resolution for current is a good idea.  Also, I had no idea there were so many spelling mistakes. Lol.  I like clean code too. All look good.

**Review by moggieuk — APPROVED** [review]
Great. Thank you.  I just haven't had the change to properly proof read but I wouldn't have caught all of these anyway.

**Review by moggieuk — APPROVED** [review]
Looks great. Thanks.

**Pull request merged**
