### PR TITLE
tip macro update v2

### PR DESCRIPTION
**Pull request by Danielstc91**
Reorganized variables into logical flow that follows SS process
Commented what each variable actually controls and ideal settings/what to look for
Default Tool change macros added standalone=0,  easier for others to change without confusion.
Added check to use Slicer ramming vs standalone(ideal for tuning without slicer)
Merged klipper variables code from Geoff's update
Renamed Cooling_Tube_Retraction to Cooling_Tube_position to follow SS naming.

Todo: SS final parking position - SS adds this last move to Park filament, but so far if set to cooling tube position(as most are doing) there have been no issues.

### CODE REVIEW

**Comment by Danielstc91** [comment]
This was tested both using standalone and then swapping to SS params. and everything works as intended.
Standalone performed 4 prints with 60-100 swaps each all without intervention. 
Printed a 40 swap print using SS tip forming, had no issues as well and formed identical tips to standalone.

**Comment by moggieuk** [comment]
Thanks for the PR.  As soon as I've finished up my auto-clog work I'll look at this.  I do feel like the tip forming can be improved.

**Comment by moggieuk** [comment]
I'm still behind on integrating this but I will as soon

**Comment by moggieuk** [comment]
Hi Daniel, I've pushed this PR into the 1.2.4 release.  Unfortunately I messed up the merge and ended adding it manually - that means you don't appear as a contributor.  Sorry about that, it was not my intention.

I tweaked a couple of things like a single line change to switch between standalone and slicer tip formation.

**Pull request closed without merging**
